In [2]:
import mysql.connector
import pandas as pd

In [3]:
host = '34.42.73.12'
user = 'root'
password = ''

In [ ]:
conexion = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    
)
cursor = conexion.cursor()
query = "SHOW DATABASES"
cursor.execute(query)

result = cursor.fetchall()

bancos = pd.DataFrame(result, columns=cursor.column_names)
display(bancos)
cursor.close()
conexion.close()

In [ ]:
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database = database,
) # estas linhas servem para criar a conexão com o banco de dados
cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = 'show tables;' # Query ou consulta desejada
cursor.execute(query) # Execução da consulta
result = cursor.fetchall() # armazenando os resultados na variável results
bancos = pd.DataFrame(result,columns=cursor.column_names) # convertendo a variável result em um df pandas chamado tabelas
display(bancos) # exibindo a tabela pandas
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

In [ ]:
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com a instância
cursor = connection.cursor() #criando o cursor para apontar para a instância
query = '''
CREATE TABLE cliente(
codcliente INT PRIMARY KEY,
nome VARCHAR(50),
cidade VARCHAR(50),
sexo CHAR(1),
estado CHAR(2),
estadocivil CHAR(1))
''' 
# Query ou consulta desejada
cursor.execute(query) # Execução da consulta
connection.commit()
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

In [ ]:
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com a instância
cursor = connection.cursor() #criando o cursor para apontar para a instância
query = '''
CREATE TABLE marca(
codmarca INT PRIMARY KEY,
marca VARCHAR(30)
);
''' 
# Query ou consulta desejada
cursor.execute(query) # Execução da consulta
connection.commit()
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

In [ ]:
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com a instância
cursor = connection.cursor() #criando o cursor para apontar para a instância
query = '''
CREATE TABLE carro(
codcarro INT PRIMARY KEY,
codmarca INT,
modelo VARCHAR(30) NOT NULL,
valor FLOAT,
FOREIGN KEY (codmarca) REFERENCES marca (codmarca)
);
''' 
# Query ou consulta desejada
cursor.execute(query) # Execução da consulta
connection.commit()
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

In [ ]:
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com a instância
cursor = connection.cursor() #criando o cursor para apontar para a instância
query = '''
CREATE TABLE aluguel(
codaluguel INT PRIMARY KEY,
codcliente INT,
codcarro INT,
data_aluguel DATE,
FOREIGN KEY (codcliente) REFERENCES cliente (codcliente),
FOREIGN KEY (codcarro) REFERENCES carro (codcarro)
);
''' 
# Query ou consulta desejada
cursor.execute(query) # Execução da consulta
connection.commit()
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

In [ ]:
# Fazendo a Conexão No Google-Cloud

conexion = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database= database
    
)
cursor = conexion.cursor()
query = "show tables"
cursor.execute(query)

result = cursor.fetchall()

bancos = pd.DataFrame(result, columns=cursor.column_names)
display(bancos)
cursor.close()
conexion.close()

In [ ]:
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com a instância
cursor = connection.cursor() #criando o cursor para apontar para a instância
query = '''
INSERT INTO cliente (codcliente, nome, cidade, sexo, estado, estadocivil)
VALUES
(1, 'Ana Silva', 'Duque de Caxias', 'F', 'RJ', 'C'),
(2, 'Bruna Pereira', 'Niterói', 'F', 'RJ', 'C'),
(3, 'Túlio Nascimento', 'Duque de Caxias', 'M', 'RJ', 'S'),
(4, 'Fernando Souza', 'Campinas', 'M', 'SP', 'S'),
(5, 'Lúcia Andrade', 'São Paulo', 'F', 'SP', 'C');
''' # Query ou consulta desejada
cursor.execute(query) # Execução da consulta
connection.commit()
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

In [ ]:
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com a instância
cursor = connection.cursor() #criando o cursor para apontar para a instância
query = '''
INSERT INTO marca (codmarca, marca) VALUES
(1, 'Ford'),
(2, 'Fiat'),
(3, 'Chevrolet'),
(4, 'Volkswagen'),
(5, 'Renault');
''' # Query ou consulta desejada
cursor.execute(query) # Execução da consulta
connection.commit()
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

In [ ]:
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com a instância
cursor = connection.cursor() #criando o cursor para apontar para a instância
query = '''
INSERT INTO carro (codcarro, modelo, codmarca, valor) VALUES
(1, 'Ka', 1, 100.00),
(2, 'Argo', 2, 150.00),
(3, 'Onix', 3, 170.00),
(4, 'Polo', 4, 150.00),
(5, 'Kwid', 5, 120.00);
''' # Query ou consulta desejada
cursor.execute(query) # Execução da consulta
connection.commit()
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

In [ ]:
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
) # estas linhas servem para criar a conexão com a instância
cursor = connection.cursor() #criando o cursor para apontar para a instância
query = '''
INSERT INTO aluguel (codaluguel, codcliente, codcarro, data_aluguel)VALUES
(1, 3, 2, '2023-04-01'),
(2, 2, 1, '2023-04-02'),
(3, 2, 1, '2023-04-03'),
(4, 2, 3, '2023-04-04'),
(5, 1, 4, '2023-04-05'),
(6, 1, 4, '2023-04-13'),
(7, 1, 1, '2023-04-15'),
(8, 5, 2, '2023-04-19'),
(9, 5, 2, '2023-04-21'),
(10,3, 1, '2023-04-25');
''' # Query ou consulta desejada
cursor.execute(query) # Execução da consulta
connection.commit()
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

In [ ]:
# Recuperando os valores da tabela cliente
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database = database,
) # estas linhas servem para criar a conexão com o banco de dados
cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = 'select * from cliente;' # Query ou consulta desejada
cursor.execute(query) # Execução da consulta
result = cursor.fetchall() # armazenando os resultados na variável results
clientes = pd.DataFrame(result,columns=cursor.column_names) # convertendo a variável result em um df pandas chamado tabelas
display(clientes) # exibindo a tabela pandas
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

In [ ]:
# Recuperando os valores da tabela carro
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database = database,
) # estas linhas servem para criar a conexão com o banco de dados
cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = 'select * from carro;' # Query ou consulta desejada
cursor.execute(query) # Execução da consulta
result = cursor.fetchall() # armazenando os resultados na variável results
carro = pd.DataFrame(result,columns=cursor.column_names) # convertendo a variável result em um df pandas chamado tabelas
display(carro) # exibindo a tabela pandas
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

In [ ]:
# Recuperando os valores da tabela carro
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database = database,
) # estas linhas servem para criar a conexão com o banco de dados
cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = 'select * from marca;' # Query ou consulta desejada
cursor.execute(query) # Execução da consulta
result = cursor.fetchall() # armazenando os resultados na variável results
marca = pd.DataFrame(result,columns=cursor.column_names) # convertendo a variável result em um df pandas chamado tabelas
display(marca) # exibindo a tabela pandas
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

In [ ]:
# Recuperando os valores da tabela carro
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database = database,
) # estas linhas servem para criar a conexão com o banco de dados
cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = 'select * from aluguel;' # Query ou consulta desejada
cursor.execute(query) # Execução da consulta
result = cursor.fetchall() # armazenando os resultados na variável results
aluguel = pd.DataFrame(result,columns=cursor.column_names) # convertendo a variável result em um df pandas chamado tabelas
display(aluguel) # exibindo a tabela pandas
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

In [ ]:
connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
) # estas linhas servem para criar a conexão com a instância
cursor = connection.cursor() #criando o cursor para apontar para a instância
query = 'create database locadora' # Query ou consulta desejada
cursor.execute(query) # Execução da consulta
connection.commit()
cursor.close() # fechando o cursor
connection.close() # fechando a conexão